### ISSUE TITLE
Cannot find module 'slick'

### ISSUE THREAD

**Issue by whereo** [devmark/ngx-slick#1]
Hey,
i just tried to install slick, following your instructions, but I get the error `/node_modules/ngx-slick/slick.component.d.ts (2,36): Cannot find module 'slick'.`
I am new to the Angular-world, so maybe i am wrong, but there is no module slick, just a slick-carousel-module?

**Comment by igghera** [comment]
Same here, the 'slick' module doesn't exist

**Comment by devmark** [comment]
Sorry , i dont testing well . 

install it again (0.1.1)

**Comment by whereo** [comment]
Thanks for the fix, installation now works and the slides are loaded, but in the console i get the error `ERROR ReferenceError: $ is not defined at index.js:45` 
Is there a `import $ from 'jquery'` or something missing?

**Comment by devmark** [comment]
Please inject jquery `<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>`  for now
i dont figure out how to inject directly.

**Comment by whereo** [comment]
jQuery is already injected

**Comment by igghera** [comment]
Works fine now on my end, I think you can close the issue. Thanks for the quick response!

**Comment by snaik2064** [comment]
I am currently using ngx-slick@0.1.1 & angular version 4.2. After any router navigation i am getting this error 

> Uncaught (in promise): TypeError: Cannot read property 'slick' of undefined
> TypeError: Cannot read property 'slick' of undefined.

& getting this console 

> removeSlide SlickItemDirective {el: ElementRef, carousel: SlickComponent}

Because of this error our projects navigation fails although slick is working fine. So is there any configuration to solve this error?

**Comment by ImTheC** [comment]
This may need to be opened again.

I tried installing ngx-slick@0.1.2, but then I got the following error:

`ERROR in /src/app/app.module.ts (9,29): Cannot find module 'ngx-slick'.`

I looked in the node_modules folder and it doesn't look right.

I fixed it by setting the version to "0.1.1" rather than "^0.1.1" in my package.json to make sure version "0.1.1" was installed. I checked the node_modules folder again and the proper files had been installed and the app was able to find the module.
